language: node_js
node_js:
    - '9.6.1'
services:
    - mongodb
before_script:
    - sleep 5
    - mongo HonorsProject --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
    - mongo HonorsProject --eval 'db.createCollection("Test");'
    - mongo HonorsProject --eval 'db.Test.createIndex({"$**":text});'
script:
    - npm run test
