language: node_js
node_js:
    - '9.6.1'
services:
    - mongodb
before_script:
    - sleep 15
    - mongo HonorsProject --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
    - mongo HonorsProject --eval 'db.createCollection("jobsheets");'
    - mongo HonorsProject --eval 'db.jobsheets.createIndex({"$**":"text"},{background:true});'
script:
    - npm run test
